version: '3.3'

services:
  web:
    image: test-modular-sample_web
    build: .docker
    volumes:
      - ./:/var/www/html
      - ./.docker/apache/sites-enabled:/etc/apache2/sites-enabled
      - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - 80:80

  composer:
    image: composer:latest
    volumes:
      - ./:/app
    working_dir: /app
    command: composer install --ignore-platform-reqs
